### ISSUE TITLE
Get version dynamically from installed package version

### ISSUE THREAD

**Issue by thekaveman** [kquinsland/lib-toggl#13]
Regarding this TODO from [`lib_toggl/__init__.py`](https://github.com/kquinsland/lib-toggl/blob/main/lib_toggl/__init__.py)

```python
# TODO build pre-commit hook or CI/CD step to ensure this tracks pyproject.toml
__version__ = "0.1.8"
```

One approach we've taken on a number of projects that works well so far, is to get the version dynamically from the installed package:

```python
from importlib.metadata import version, PackageNotFoundError

try:
    __version__ = version("lib-toggl")
except PackageNotFoundError:
    # package is not installed, set fallback, etc.
    pass
```

This allows you to maintain the version string in `pyproject.toml`, and package installers still get the expected version from `lib_toggl.__version__`, without extra CI/CD steps.

**Comment by kquinsland** [comment]
TIL about the `version()` call from `importlib`.
This has a lot of upside and - as long as the `toml` is also distributed along with the `py` code - should work beautifully with only a small new dependency (but I have only once _ever_ seen a standard python dist that _didn't_ ship `importlib` as well... so not really a heavy/external dependency...)

**Comment by thekaveman** [comment]
Yeah! I think [`importlib` is part of standard Python as of 3.1](https://docs.python.org/3/library/importlib.html), so that shouldn't pose too much of a problem for anyone.

> as long as the `toml` is also distributed along with the `py` code...

Maybe I'm not following, can you say more about this? When the source is built into a `.whl` for publishing on PyPI, the version metadata should be a part of that package, without the need to ship the `.toml` right?

My ignorance here may also be due to not having worked with any Home Assistant frameworks, so I'm more coming from a "generic python library" perspective.

**Comment by kquinsland** [comment]
> so I'm more coming from a "generic python library" perspective.

No, this isn't a HA specific anachronism/oddity :D.


While not ideal, the "just git clone $someRepo at $someSpecificTag" approach is _decently common_ for distribution anytime you a) need private packages b) do not have the time/money/resources/management-buy-in to set up a proper private python package system.

For _this_ repo, it's not really a concern... but there are other repos that I have worked with where you'd need to do something like:

```python3
try:
    __version__ = version("lib-example")
except PackageNotFoundError:
    __version__ = go_find_the_toml_file_and_extract_that_way("lib-example")
```

**Comment by kquinsland** [comment]
> If I were to put together a little PR for this

`None` makes the most sense.
